-- MySQL Script generated by MySQL Workbench
-- 05/04/15 23:11:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogsystem_softuni
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogsystem_softuni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogsystem_softuni` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blogsystem_softuni` ;

-- -----------------------------------------------------
-- Table `blogsystem_softuni`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogsystem_softuni`.`Users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogsystem_softuni`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogsystem_softuni`.`Posts` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` NVARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  INDEX `fk_Posts_Users1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `blogsystem_softuni`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogsystem_softuni`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogsystem_softuni`.`Comments` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `content` NVARCHAR(500) NOT NULL,
  `Post_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  INDEX `fk_Comments_Posts_idx` (`Post_id` ASC),
  INDEX `fk_Comments_Users1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Comments_Posts`
    FOREIGN KEY (`Post_id`)
    REFERENCES `blogsystem_softuni`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`User_id`)
    REFERENCES `blogsystem_softuni`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogsystem_softuni`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogsystem_softuni`.`Tags` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogsystem_softuni`.`Tags_has_Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogsystem_softuni`.`Tags_has_Posts` (
  `Tag_id` INT NOT NULL,
  `Post_id` INT NOT NULL,
  PRIMARY KEY (`Tag_id`, `Post_id`),
  INDEX `fk_Tags_has_Posts_Posts1_idx` (`Post_id` ASC),
  INDEX `fk_Tags_has_Posts_Tags1_idx` (`Tag_id` ASC),
  CONSTRAINT `fk_Tags_has_Posts_Tags1`
    FOREIGN KEY (`Tag_id`)
    REFERENCES `blogsystem_softuni`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_Posts_Posts1`
    FOREIGN KEY (`Post_id`)
    REFERENCES `blogsystem_softuni`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
